version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: muebleria-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: muebleria_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: muebleria-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/muebleria_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build: ./frontend
    container_name: muebleria-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: